%% Convolve atmospheric transmission: Testing one column at one time
crism_convolve_hitran_abscoef('40A2','Columns',23, ...
    'ABSCOEF_DIR', '/Volumes/LaCie5TB/out/mcd', 'mcd_ver', '6_1', ...
    'h2o_scale', 1.0, 'additional_suffix', '');



%% Test the fit of the convolved ATM at one column on a bland image% First test using 
% sabcondv5_pub_column_test
%   second input is the column index
%   'debug', true        (debug mode, you can see plot of spectra and errors)
%   'DEBUG_L_PLOT',200   (line index of the spectrum shown in figures in
%                         debug mode)
% Set 'SAVE_FILE',false not to save anything.
% Make sure 
% 'varargin_T',{'additional_suffix','mean_abscoef_hitran_v7_1_1_idx0t0_ctr','dirpath','./TList'}
% is correct, especially directory path
% Library option may be important
% 'OPT_CRISMSPCLIB',0, 'OPT_RELAB', 0, 'OPT_CRISMTYPELIB',0,'OPT_SPLIBUSGS',0, ...
%     'OPT_ICELIB',6, 'OPT_SURFICELIB', 7,

crism_obs_ref = CRISMObservation('40A2','SENSOR_ID','L');
TRRIFdata_ref = CRISMdata(crism_obs_ref.info.basenameIF,'');
[out_t1c] = sabcondv5_pub_column_test('40A2', 55, ...
    'FFC_MODE', false, 'FFC_IF_COUNTER', 1,...
    'WEIGHT_MODE', 1, 'cal_bias_cor', 0,...
    't_mode', 5, 'obs_id_T', TRRIFdata_ref.basename, 'varargin_T', { ...
        'additional_suffix','mean_MCDv6_1_scena1_abscoef_2020_voigt_ctr', ...
        'dirpath', '/Users/itohy1/data/T' ...
    },...
    'lambda_a', 0.0, 'opt_img', 'TRRD', 'OPTBP', 'none',...
    'nIter', 2, 'Bands_Opt', 6, 'Library_opt', 'full', ...
    'OPT_CRISMSPCLIB', 0, 'OPT_RELAB', 0, 'OPT_CRISMTYPELIB', 0, ...
    'OPT_SPLIBUSGS',0, 'OPT_ICELIB', [], 'OPT_SURFICELIB', [], ...
    'PRECISION', 'double', 'PROC_MODE', 'CPU_2',...
    'debug', true, 'DEBUG_L_PLOT', 175, ... 383, ...285,...
    'lambda_update_rule', 'L1SUM',...
    'SAVE_FILE', false, ...
    'T_UPDATE', 2, 'logT_neg', false, 'opt_bands_ignore_init', 'none', ...
    'include_ice', true);

%% Batch processing of convolution.

crism_convolve_hitran_abscoef('40A2', ...
    'ABSCOEF_DIR', '/Volumes/LaCie5TB/out/mcd', 'mcd_ver', '6_1');

%%
crism_obs_ref = CRISMObservation('40A2','SENSOR_ID','L');
TRRIFdata_ref = CRISMdata(crism_obs_ref.info.basenameIF,'');
[out_bland2] = sabcondv5_pub('40FF', ...
    'FFC_MODE', false, 'FFC_IF_COUNTER', 1, ...'LINES',100:200,...
    'WEIGHT_MODE', 1, 'cal_bias_cor', 0, ...
    ... % Transmission option
    't_mode', 5, 'obs_id_T', TRRIFdata_ref.basename, 'varargin_T', { ...
        'additional_suffix', 'mean_MCDv6_1_scena1_abscoef_2020_voigt_ctr', ...
        'dirpath', '/Users/itohy1/data/T' ...
    },...
    'lambda_a', 0.02, 'opt_img', 'TRRD', 'OPTBP', 'none',...
    ... % Library option
    'Library_opt', 'full', ...
    'OPT_CRISMSPCLIB',0, 'OPT_RELAB', 0, 'OPT_CRISMTYPELIB', 0, ...
    'OPT_SPLIBUSGS', 0, 'OPT_ICELIB', [], 'OPT_SURFICELIB', [], ...
    ...
    'nIter', 2, 'Bands_Opt', 6,...
    'PRECISION', 'double', 'PROC_MODE', 'CPU_2',...
    'debug', false,...
    'lambda_update_rule', 'L1SUM',...
    'SAVE_FILE',true, 'additional_suffix', 'mcd6_1s01',...
    'save_pdir','./results/',...
    'T_UPDATE', 2, 'logT_neg', false, 'opt_bands_ignore_init', 'none', ...
    'include_ice', true);


% Make sure directory path.
TList = permute(out_bland2.T_est,[3,2,1]);
fname = ['TList_' TRRIFdata_ref.basename out_bland2.settings.suffix ...
         '.mat'];
fpath = joinPath('./data/T',fname);
save(fpath,'TList');
%% check the results
obs_id = '40A2';
crism_obs = CRISMObservation(obs_id,'sensor_id','L');
TRR3dataset = CRISMTRRdataset(crism_obs.info.basenameIF,'');
pdir5 = './results/';
dir_sab5 = joinPath(pdir5,TRR3dataset.trr3if.dirname);
sabcond_data5 = SABCONDdataset(TRR3dataset.trrdif.basename,dir_sab5,...
    'suffix','sabcondpub_v1_mcd6_1s01');
TRR3dataset.catif.readWAi_fromCRISMdata_parent();
TRR3dataset.catif.wa = TRR3dataset.catif.wa / 1000;
%%
sabcond_data5.nr_ds.set_rgb();
sabcond_data5.cor.wa = TRR3dataset.catif.wa;
sabcond_data5.ori.wa = TRR3dataset.catif.wa;
h1 = ENVIRasterMultview({sabcond_data5.nr_ds.RGB.CData_Scaled},{ ...
    ...{TRR3dataset.catif,'name','CAT IF','AVERAGE_WINDOW',[1,1]}, ...
    {sabcond_data5.nr_ds,'name','v5','AVERAGE_WINDOW',[1,1],'shift',0.00,'varargin_plot',{'.-'}},...
    },...
'SPC_XLIM',[1.100 2.600],...
'varargin_ImageStackView',{'Ydir','reverse'});

%% Test on target image

crism_obs_ref = CRISMObservation('40A2','SENSOR_ID','L');
TRRIFdata_ref = CRISMdata(crism_obs_ref.info.basenameIF,'');
c = 607; l = 225;
c = 500; l = 200;
c=254; l = 520; % c=254; l = 200;
c = 500; l = 200;
c=602; l=518;
% c=284; l-327;
c=528; l=516;
c=100; l=100;
c=368; l=234;c=334; l=516;
c=568; l=274;c=341; l=516;
c=574;
[out_t1c] = sabcondv5_pub_column_test('40FF', c, ...
    'FFC_MODE',false,'FFC_IF_COUNTER',1,...'LINES',100:200,...
    'WEIGHT_MODE',1,'cal_bias_cor',0,...
    ... Transmission options
    't_mode', 5, 'obs_id_T', TRRIFdata_ref.basename,...
    'varargin_T',{ ...
        'additional_suffix' ,'sabcondpub_v1_mcd6_1s01', ...
        'dirpath', '/Users/itohy1/data/T' ...
        },...
    'lambda_a',0.02,'opt_img','TRRD','OPTBP','none',...
    'nIter',2,'Bands_Opt',6, ...
    ... Library Options
    'Library_opt','full', ...
    'OPT_CRISMSPCLIB',1, 'OPT_RELAB', 1, 'OPT_CRISMTYPELIB', 6, ...
    'OPT_SPLIBUSGS', 4, 'OPT_ICELIB', [], 'OPT_SURFICELIB', [], ...
    ...
    'PRECISION','double','PROC_MODE','CPU_2',...
    'debug',true,'DEBUG_L_PLOT',l,...
    'lambda_update_rule','L1SUM',...
    'SAVE_FILE',false,...
    'T_UPDATE',2,'logT_neg',false,'opt_bands_ignore_init','none', ...
    'include_ice', true);


%% Batch processing on target image
crism_obs_ref = CRISMObservation('40A2','SENSOR_ID','L');
TRRIFdata_ref = CRISMdata(crism_obs_ref.info.basenameIF,'');
[out_tar] = sabcondv5_pub('40FF', ...
    'FFC_MODE',false,'FFC_IF_COUNTER',1, ...'LINES',100:200,...
    'WEIGHT_MODE',1,'cal_bias_cor',0, ...
    ... Transmission options
    't_mode', 5, 'obs_id_T', TRRIFdata_ref.basename,...
    'varargin_T',{ ...
        'additional_suffix','sabcondpub_v1_mcd6_1s01_wsaice_230_a', ...
        'dirpath', '/Users/itohy1/data/T' ...
        },...
    'lambda_a',0.002,'opt_img','TRRD','OPTBP','none',...
    'nIter',2,'Bands_Opt',6, ...
    ... Library Options
    'Library_opt','full', ...
    'OPT_CRISMSPCLIB',1, 'OPT_RELAB', 1, 'OPT_CRISMTYPELIB', 6, ...
    'OPT_SPLIBUSGS',4, 'OPT_ICELIB', [], 'OPT_SURFICELIB', [], ...
    ...
    'PRECISION','double','PROC_MODE','CPU_2',...
    'debug', false, ...'DEBUG_L_PLOT',l,...
    'lambda_update_rule','L1SUM',...
    'SAVE_FILE',false,...
    'SAVE_FILE',true, 'additional_suffix', 'mcd6_1s01_40A2',...
    'save_pdir','./results/',...
    'T_UPDATE', 2, 'logT_neg', false, 'opt_bands_ignore_init', 'none', ...
    'include_ice', true);

% a means fixed for bad spectra

%% check the results
obs_id = '40FF';
crism_obs = CRISMObservation(obs_id,'sensor_id','L');
TRR3dataset = CRISMTRRdataset(crism_obs.info.basenameIF,'');
pdir5 = './results/';
dir_sab5 = joinPath(pdir5,TRR3dataset.trr3if.dirname);
sabcond_data5 = SABCONDdataset(TRR3dataset.trrdif.basename,dir_sab5,...
    'suffix','sabcondpub_v1_mcd6_1s01_40A2');
TRR3dataset.catif.readWAi_fromCRISMdata_parent();
TRR3dataset.catif.wa = TRR3dataset.catif.wa / 1000;
%%
sabcond_data5.nr.set_rgb();
sabcond_data5.nr.wa = TRR3dataset.catif.wa;
h1 = ENVIRasterMultview({sabcond_data5.nr.RGB.CData_Scaled},{ ...
    {sabcond_data5.nr,'name','v5 wsaice','AVERAGE_WINDOW',[1,1],'shift',0.00,'varargin_plot',{'.-'}},...
    },...
'SPC_XLIM',[1.000 2.600],...
'varargin_ImageStackView',{'Ydir','reverse'});


%% Post Processing


%%
obs_id = '40FF';
obs_info = crism_get_obs_info_v2(obs_id,'download_trrif_cs',2);
csi = obs_info.central_scan_info.indx;
TRR3dataset = CRISMTRRdataset(obs_info.sgmnt_info(csi).L.trr.IF{1},'');
TRR3dataset.trr3if.load_basenamesCDR();
WAdata = TRR3dataset.trr3if.readCDR('WA'); WAdata.readimgi();
bands = crmsab_genBands_v2(WAdata.prop.wavelength_filter,6,WAdata.prop.binning,WAdata.prop.sclk);

pdir5 = './results/';
dir_sab5 = joinPath(pdir5,TRR3dataset.trr3if.dirname);
sabcond_data5_1 = SABCONDdataset(TRR3dataset.trrdif.basename,dir_sab5,...
    'suffix','sabcondpub_v1_mcd6_1s01_40A2');
%% photometric correction
DEdata = CRISMDDRdata(obs_info.sgmnt_info(csi).L.ddr.DE{1}, '');
crism_photocor_wrapper(sabcond_data5_1.nr_ds, DEdata);

%% Replace values
sabcond5_1_nr_ds_pht1 = CRISMdataCAT(...
    [sabcond_data5_1.nr_ds.basename, '_phot1'], ...
    sabcond_data5_1.nr_ds.dirpath);

crism_replace_value_wrapper(sabcond5_1_nr_ds_pht1);







